using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class Admission : System.Web.UI.Page
    {
         SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            TextBox3.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                reset();

            }
        }
        private void reset()
        {
            DropDownList1.ClearSelection();
            txtProseg.Text = string.Empty;
            classname.ClearSelection();
            TextBox2.Text = string.Empty;
            txtProweig.Text = string.Empty;
            txtAvbstoc.Text = string.Empty;
            Textbox1.Text = string.Empty;
            txtProcode.Text = string.Empty;
        }
        private void autogenerated()
        {
            string code = "AdmissionId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(Admission_Id) from Admission", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtId.Text = code + i.ToString();
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into Admission values('" + txtId.Text.Trim() + "','" + TextBox3.Text.Trim() + "','" + txtProseg.Text.Trim() + "','" + classname.SelectedValue.Trim() + "','" + TextBox2.Text.Trim() + "','" + DropDownList1.SelectedValue.Trim() + "','" + txtProweig.Text.Trim() + "','" + txtAvbstoc.Text.Trim() + "','" + Textbox1.Text.Trim() + "','" + txtProcode.Text.Trim() + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            reset();
            autogenerated();
            Gridview1.DataBind();
        }
    }
}