using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class Branchs : System.Web.UI.Page
    {
      
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                autogenerated();
                reset();

            }
        }
        private void reset()
        {
            txtProseg.Text = string.Empty;
            txtProcode.Text = string.Empty;
            txtFuel.Text = string.Empty;
        }
        private void autogenerated()
        {
            string code = "School-0";
            string strconn = ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(BranchId) from Branches", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtId.Text = code + i.ToString();
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into Branches(BranchId,BranchName,PrincipalName,Address)values('" + txtId.Text.Trim() + "','" + txtProseg.Text.Trim() + "','" + txtProcode.Text.Trim() + "','" + txtFuel.Text.Trim() + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            Response.Write("Insertion Successful!!!!!!!");
            reset();
            autogenerated();
            Gridview1.DataBind();
        }
    }
}
