using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class Enquiry1 : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            TextBox2.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                reset();

            }
        }
        private void reset()
        {
            txtId.Text = string.Empty;
            txtProseg.Text = string.Empty;
            txtFuel.Text = string.Empty;
            txtProcode.Text = string.Empty;
            txtProdis.Text = string.Empty;
            txtProweig.Text = string.Empty;
        }
        private void autogenerated()
        {
            string code = "visitorId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(PersionId) from Enquiry", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TextBox1.Text = code + i.ToString();
        }
        protected void Button_Click(object sender, EventArgs e)

        {
            DateTime a = new DateTime();
            a = DateTime.Now;
            txtProweig.Text = a.ToString("HH:mm:ss");
            SqlCommand Comm = new SqlCommand("insert into Enquiry values('" + TextBox1.Text.Trim() + "','" + TextBox2.Text.Trim() + "','" + txtId.Text.Trim() + "','" + txtProseg.Text.Trim() + "','" + txtFuel.Text.Trim() + "','" + txtProweig.Text.Trim() + "','" + txtProcode.Text.Trim() + "','" + txtProdis.Text.Trim() + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            GridView1.DataBind();
            reset();
            autogenerated();

        }

    }
}