using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class Feemaster : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            txtdate.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
                //Classgenerate();
                student();
            }
        }

        //private void Classgenerate()
        //{
        //    dd.Items.Insert(0, new System.Web.UI.WebControls.ListItem("Class", "-1"));
        //    dd.AppendDataBoundItems = true;

        //    string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;

        //    String strQuery = "select Class from Classes";
        //    SqlConnection con = new SqlConnection(constr);

        //    SqlCommand cmd = new SqlCommand();
        //    cmd.CommandType = CommandType.Text;
        //    cmd.CommandText = strQuery;
        //    cmd.Connection = con;
        //    try
        //    {
        //        con.Open();
        //        dd.DataSource = cmd.ExecuteReader();
        //        dd.DataTextField = "Class";
        //        dd.DataValueField = "Class";
        //        dd.DataBind();
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //    finally
        //    {
        //        con.Close();
        //        con.Dispose();
        //    }
        //}

        private void autogenerated()
        {
            string code = "FeeId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(FeeId) from FeeDetails", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtId.Text = code + i.ToString();
        }

        protected void Reset()
        {
            //DropDownList1.ClearSelection();
            //txtStdid.Text = string.Empty;
            Txtadmno.Text = string.Empty;
            txtStdName.Text = string.Empty;
            TextBox2.Text = string.Empty;
            TextBox1.Text = string.Empty;
            Txtadmno.Text = string.Empty;
            txtcName.Text = string.Empty;
            txtTfee.Text = string.Empty;
            txtFpaid.Text = string.Empty;
            txtPaidby.Text = string.Empty;
            txtdiscount.Text = string.Empty;

        }
        private void student()
        {
            DDstudent.Items.Insert(0, new System.Web.UI.WebControls.ListItem("Select Id", "-1"));
            DDstudent.AppendDataBoundItems = true;
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            string strQuery = "select StudentId from StdRegistation";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                DDstudent.DataSource = cmd.ExecuteReader();
                DDstudent.DataTextField = "StudentId";
                DDstudent.DataValueField = "StudentId";
                DDstudent.DataBind();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }
        protected void DDstudent_SelectedIndexChanged(object sender, EventArgs e)
        {
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;

            string strQuery = "select AdmissionNo,StudentName,Class,Section,Fee_Details from StdRegistation where StudentId = @StudentId";

            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.Parameters.AddWithValue("@StudentId", DDstudent.SelectedItem.Value);
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                   Txtadmno.Text = sdr["AdmissionNo"].ToString();
                    txtStdName.Text = sdr["StudentName"].ToString();
                   Txtclass.Text = sdr["Class"].ToString();
                   Txtsection.Text = sdr["Section"].ToString();
                    txtTfee.Text = sdr["Fee_Details"].ToString();
                  
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into Fees values('" + txtId.Text + "','" + txtdate.Text + "','" + DDstudent.SelectedItem.Text + "','"+Txtadmno.Text+"','" + txtStdName.Text + "','" + Txtclass.Text + "','" + Txtsection.Text + "','" + txtTfee.Text + "','" + txtdiscount.Text + "','" + TextBox2.Text + "','" + txtFpaid.Text + "','" + TextBox1.Text + "','" + txtPaidby.Text + "','" + txtcName.Text + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            Reset();
            autogenerated();
            GridView1.DataBind();
        }

        protected void txtTfee_TextChanged(object sender, EventArgs e)
        {
            if ((!string.IsNullOrEmpty(txtTfee.Text)) && (!string.IsNullOrEmpty(txtdiscount.Text)))
            {
                TextBox2.Text = (Convert.ToInt32(txtTfee.Text) - Convert.ToInt32(txtdiscount.Text)).ToString();
            }
        }

        protected void TextBox2_TextChanged(object sender, EventArgs e)
        {
            if ((!string.IsNullOrEmpty(txtTfee.Text)) && (!string.IsNullOrEmpty(txtdiscount.Text)))
            {
                TextBox2.Text = (Convert.ToInt32(txtTfee.Text) - Convert.ToInt32(txtdiscount.Text)).ToString();
            }
        }

        protected void TextBox2_TextChanged1(object sender, EventArgs e)
        {
            if ((!string.IsNullOrEmpty(TextBox2.Text)) && (!string.IsNullOrEmpty(txtFpaid.Text)))
            {
                TextBox1.Text = (Convert.ToInt32(TextBox2.Text) - Convert.ToInt32(txtFpaid.Text)).ToString();
            }
        }

        protected void txtFpaid_TextChanged(object sender, EventArgs e)
        {
            if ((!string.IsNullOrEmpty(TextBox2.Text)) && (!string.IsNullOrEmpty(txtFpaid.Text)))
            {
                TextBox1.Text = (Convert.ToInt32(TextBox2.Text) - Convert.ToInt32(txtFpaid.Text)).ToString();
            }
        }

       
    }
    
}