using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class Holidaymaster : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {

            txtDate.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                reset();
            }
        }
        private void reset()
        {
            ddl.ClearSelection();
            dd2.ClearSelection();
            txtNodays.Text = string.Empty;
            txtFdate.Text = string.Empty;
            txtTdate.Text = string.Empty;
        }
        private void autogenerated()
        {
            string code = "HolidayId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(HolidayId) from Holidays", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtId.Text = code + i.ToString();
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into Holidays values('" + txtId.Text + "','" + txtDate.Text + "','" + ddl.Text + "','" + dd2.Text + "','" + txtNodays.Text + "','" + txtFdate.Text + "','" + txtTdate.Text + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            reset();
            autogenerated();
            GridView1.DataBind();
        }
    }
}