using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

namespace SchoolProject
{
    public partial class Inventory_lab : System.Web.UI.Page
    {
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        string str;
        int count;
        SqlCommand com;
        protected void Page_Load(object sender, EventArgs e)
        {
            txtdate.Text = DateTime.Now.Date.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }
        }

        private void Reset()
        {
            txtComputers.Text = string.Empty;
            txtChairs.Text = string.Empty;
            txtTables.Text = string.Empty;
            txtRefBooks.Text = string.Empty;
            txtac.Text = string.Empty;
            txtracks.Text = string.Empty;
            txtheadset.Text = string.Empty;
        }

        private void autogenerated()
        {
            string code = "InventoryId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(LabId) from Inventory_lab", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtId.Text = code + i.ToString();
        }

        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand com = new SqlCommand("insert into Inventory_lab values('" + TxtId.Text.Trim() + "','" + txtdate.Text.Trim() + "','" + txtComputers.Text.Trim() + "','" + txtChairs.Text.Trim() + "','" + txtTables.Text.Trim() + "','" + txtRefBooks.Text.Trim() + "','" + txtac.Text.Trim() + "','" + txtracks.Text.Trim() + "','" + txtheadset.Text.Trim() + "')", con);
            con.Open();
            com.ExecuteNonQuery();
            con.Close();
            autogenerated();
            Reset();
        }
    }
}