using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

namespace SchoolProject
{
    public partial class Inventory_class : System.Web.UI.Page
    {
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            txtdate.Text = DateTime.Now.Date.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }
        }

        private void Reset()
        {
            txtChairs.Text = string.Empty;
            txttables.Text = string.Empty;
            txtProjectors.Text = string.Empty;
            txtFans.Text = string.Empty;
            txtLights.Text = string.Empty;
            txtlabtops.Text = string.Empty;
            txtdustbins.Text = string.Empty;
            txtracks.Text = string.Empty;
        }

        private void autogenerated()
        {
            string code = "InventoryId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(InventoryId) from Inventory_class", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtId.Text = code + i.ToString();
        }

        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand com = new SqlCommand("insert into Inventory_class values('" + TxtId.Text.Trim() + "','" + txtdate.Text.Trim() + "','" + txtChairs.Text.Trim() + "','" + txttables.Text.Trim() + "','" + txtProjectors.Text.Trim() + "','" + txtFans.Text.Trim() + "','" + txtLights.Text.Trim() + "','" + txtlabtops.Text.Trim() + "','" + txtdustbins.Text.Trim() + "','" + txtracks.Text.Trim() + "')", con);
            con.Open();
            com.ExecuteNonQuery();
            con.Close();
            Reset();
            autogenerated();
        }
    }
}