using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

namespace SchoolProject
{
    public partial class LibraryBookIssuesPage : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            txtDate.Text = DateTime.Now.ToShortDateString();

            if (!IsPostBack)
            {
                autogenerated();
                Reset();
                studentid();
                bookid();
            }
        }

        private void bookid()
        {
            DDbookid.Items.Insert(0, new System.Web.UI.WebControls.ListItem("Select Id", "-1"));
            DDbookid.AppendDataBoundItems = true;
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            string strQuery = "select Book_Id from AddBook";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                DDbookid.DataSource = cmd.ExecuteReader();
                DDbookid.DataTextField = "Book_Id";
                DDbookid.DataValueField = "Book_Id";
                DDbookid.DataBind();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }

        private void studentid()
        {
            DDstudent.Items.Insert(0, new System.Web.UI.WebControls.ListItem("Select Id", "-1"));
            DDstudent.AppendDataBoundItems = true;
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            string strQuery = "select StudentId from StdRegistation";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                DDstudent.DataSource = cmd.ExecuteReader();
                DDstudent.DataTextField = "StudentId";
                DDstudent.DataValueField = "StudentId";
                DDstudent.DataBind();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }

        private void Reset()
        {
            txtBookName.Text = string.Empty;
            txtBookNum.Text = string.Empty;
            DDbookid.ClearSelection();
            DDstudent.ClearSelection();
            txtclass.Text = string.Empty;
            txtcopies.Text = string.Empty;
            txtstock.Text = string.Empty;
            txtprice.Text = string.Empty;
            txtclass1.Text = string.Empty;
            txtstdname.Text = string.Empty;
            txtsection.Text = string.Empty;
            txtReturn.Text = string.Empty;

        }

        private void autogenerated()
        {
            string code = "IssueId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(IssueId) from BookIssues", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtid.Text = code + i.ToString();
        }

        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Cmd = new SqlCommand("insert into BookIssues(IssueId,Date,Book_Id,Book_Name,Book_Number,class,copies,stock,price,Student_Id,studentname,class1,section,quality,Return_Date,librarianame) values ('" + txtid.Text.Trim() + "','" + txtDate.Text.Trim() + "','" + DDbookid.SelectedValue.ToString() + "','" + txtBookName.Text.Trim() + "','" + txtBookNum.Text.Trim() + "','" + txtclass.Text.Trim() + "','" + txtcopies.Text.Trim() + "','" + txtstock.Text.Trim() + "','" + txtprice.Text.Trim() + "','" + DDstudent.SelectedValue.ToString() + "','" + txtstdname.Text.Trim() + "','" + txtclass1.Text.Trim() + "','" + txtsection.Text.Trim() + "','" + txtqnty.Text.Trim() + "','" + txtReturn.Text.Trim() + "','" + txtliname.Text.Trim() + "')", Conn);
            Conn.Open();
            Cmd.ExecuteNonQuery();
            Conn.Close();
            autogenerated();

            message.Text = "Values Inserted";

            int k = (Convert.ToInt32(txtstock.Text) - Convert.ToInt32(txtqnty.Text));
            SqlCommand cmd = new SqlCommand("Update AddBook set AvailableStock = '" + k.ToString() + "'", Conn);
            Conn.Open();
            cmd.ExecuteNonQuery();
            Conn.Close();
            Reset();
        }

        protected void DDbookid_SelectedIndexChanged(object sender, EventArgs e)
        {
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            string strQuery = "select Book_Name,Book_Number,Class,TotalCopies,Price,AvailableStock from AddBook where Book_Id = @Book_Id";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.Parameters.AddWithValue("@Book_Id", DDbookid.SelectedItem.Value);
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {

                    txtBookName.Text = sdr["Book_Name"].ToString();
                    txtBookNum.Text = sdr["Book_Number"].ToString();
                    txtclass.Text = sdr["Class"].ToString();
                    txtcopies.Text = sdr["TotalCopies"].ToString();
                    txtprice.Text = sdr["Price"].ToString();
                    txtstock.Text = sdr["AvailableStock"].ToString();

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }

        protected void DDstudent_SelectedIndexChanged(object sender, EventArgs e)
        {
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;

            string strQuery = "select StudentName,Class,Section from StdRegistation where StudentId = @StudentId";

            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.Parameters.AddWithValue("@StudentId", DDstudent.SelectedItem.Value);
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {

                    txtstdname.Text = sdr["StudentName"].ToString();
                    txtclass1.Text = sdr["Class"].ToString();
                    txtsection.Text = sdr["Section"].ToString();

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }
    }
}