using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

namespace SchoolProject
{
    public partial class LibraryBookReturnsPage : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            txtDate.Text = DateTime.Now.ToShortDateString();

            if (!IsPostBack)
            {
                autogenerated();
                Reset();
                IssueId();

            }
        }

        private void IssueId()
        {
            DDIssue.Items.Insert(0, new System.Web.UI.WebControls.ListItem("Select Id", "-1"));
            DDIssue.AppendDataBoundItems = true;
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            string strQuery = "select IssueId from BookIssues";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                DDIssue.DataSource = cmd.ExecuteReader();
                DDIssue.DataTextField = "IssueId";
                DDIssue.DataValueField = "IssueId";
                DDIssue.DataBind();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
        }

        private void Reset()
        {
            txtBookid.Text = string.Empty;
            txtBookName.Text = string.Empty;
            txtBookNum.Text = string.Empty;
            txtclass1.Text = string.Empty;
            txtliname.Text = string.Empty;
            DDIssue.ClearSelection();
            txtReturn.Text = string.Empty;
            txtsection.Text = string.Empty;
            txtstdId.Text = string.Empty;
            txtstdname.Text = string.Empty;
            txtdate1.Text = string.Empty;
            TextBox1.Text = string.Empty;
        }

        private void autogenerated()
        {
            string code = "ReturnId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(ReturnId) from BookReturns", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            txtId.Text = code + i.ToString();
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand cmd = new SqlCommand("insert into BookReturns(ReturnId,Date,IssueId,Issuedate,Book_Id,Book_Number,Book_Name,class,Student_Id,studentname,class1,section,quality,Return_Date,librarianame) values('" + txtId.Text + "','" + txtDate.Text + "','" + DDIssue.SelectedItem.ToString() + "','" + txtdate1.Text + "','" + txtBookid.Text + "','" + txtBookNum.Text + "','" + txtBookName.Text + "','" + TextBox1.Text + "','" + txtstdId.Text + "','" + txtstdname.Text + "','" + txtclass1.Text + "','" + txtsection.Text + "','" + txtqnty.Text + "','" + txtReturn.Text + "','" + txtliname.Text + "')", Conn);
            Conn.Open();
            cmd.ExecuteNonQuery();
            Conn.Close();
            autogenerated();
            int k = (Convert.ToInt32(txtstock.Text) + Convert.ToInt32(txtqnty.Text));
            SqlCommand cmd1 = new SqlCommand("Update AddBook set AvailableStock = '" + k.ToString() + "' where Book_Id='" + txtBookid.Text + "'", Conn);
            Conn.Open();
            cmd1.ExecuteNonQuery();
            Conn.Close();
            Reset();

        }

        protected void DDIssue_SelectedIndexChanged(object sender, EventArgs e)
        {
            string constr = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;

            string strQuery = "select Book_Id,Date,Book_Name,Book_Number,class1,Student_Id,studentname,class,section,quality,Return_Date,librarianame from BookIssues where IssueId = @IssueId";

            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand();
            cmd.Parameters.AddWithValue("@IssueId", DDIssue.SelectedItem.Value);
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = strQuery;
            cmd.Connection = con;
            try
            {
                con.Open();
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    txtBookid.Text = sdr["Book_Id"].ToString();
                    txtdate1.Text = sdr["Date"].ToString();
                    txtBookName.Text = sdr["Book_Name"].ToString();
                    txtBookNum.Text = sdr["Book_Number"].ToString();
                    TextBox1.Text = sdr["class"].ToString();
                    txtsection.Text = sdr["section"].ToString();
                    //txtstock.Text = sdr["stocks"].ToString();
                    txtclass1.Text = sdr["class1"].ToString();
                    txtReturn.Text = sdr["Return_Date"].ToString();
                    txtstdname.Text = sdr["studentname"].ToString();
                    txtstdId.Text = sdr["Student_Id"].ToString();
                    txtqnty.Text = sdr["quality"].ToString();
                    txtliname.Text = sdr["librarianame"].ToString();

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            SqlCommand cmd1 = new SqlCommand("select * from AddBook where Book_Id= '" + txtBookid.Text + "'", Conn);
            Conn.Open();
            SqlDataReader sr = cmd1.ExecuteReader();

            while (sr.Read())
            {
                txtstock.Text = sr["AvailableStock"].ToString();
            }
            Conn.Close();
        }
    }
}