using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class QuizReg : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            TxtDate.Text = System.DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }
        }

        private void autogenerated()
        {
            string code = "QuizId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(QuizId) from Quiz", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtQId.Text = code + i.ToString();
        }

        protected void Reset()
        {
            TxtQName.Text = string.Empty;
            TxtClass.Text = string.Empty;
            TxtSection.Text = string.Empty;
            TxtQType.Text = string.Empty;
            TxtWinner.Text = string.Empty;
            TxtRunner.Text = string.Empty;
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into Quiz values('" + TxtQId.Text + "','" + TxtDate.Text + "','" + TxtQName.Text + "','" + TxtClass.Text + "','" + TxtSection.Text + "','" + TxtQType.Text + "','" + TxtWinner.Text + "','" + TxtRunner.Text + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            Reset();
            autogenerated();
        }
    }
}