using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

namespace SchoolProject
{
    public partial class SchoolStaffRegistration : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SMSConnectionString"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }

            TxtDate.Text = System.DateTime.Now.ToShortDateString();
        }
        protected void Reset()
        {
            TxtDate.Text = string.Empty;
            TxtName.Text = string.Empty;
            TxtGender.ClearSelection();
            TxtDesgination.Text = string.Empty;
            TxtDepartment.Text = string.Empty;
            TxtSubject.Text = string.Empty;
            TxtExperience.Text = string.Empty;
            TxtEmail.Text = string.Empty;
            TxtReligion.Text = string.Empty;
            DropDownList1.ClearSelection();
            TxtJoinDate.Text = string.Empty;
            TxtPhone.Text = string.Empty;
            TxtAltNumber.Text = string.Empty;
            TxtAddress.Text = string.Empty;
            TxtStatus.ClearSelection();
            txtusername.Text = string.Empty;
            txtpwd.Text = string.Empty;

        }
        private void autogenerated()
        {
            string code = "STF0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(Staf_Id) from StaffRegistration", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtStaffId.Text = code + i.ToString();
        }





        protected void SubmitButton_Click(object sender, EventArgs e)
        {
            if (FileUpload1.HasFile)
                if (FileUpload2.HasFile)
                    if (FileUpload3.HasFile)
                    {
                        string str = FileUpload1.FileName;
                        string str1 = FileUpload2.FileName;
                        string str2 = FileUpload3.FileName;
                        FileUpload1.PostedFile.SaveAs(Server.MapPath("~/UploadedFiles/" + str));
                        FileUpload2.PostedFile.SaveAs(Server.MapPath("~/UploadedFiles/" + str1));
                        FileUpload3.PostedFile.SaveAs(Server.MapPath("~/UploadedFiles/" + str2));
                        string Photo = "~/UploadedFiles/" + str.ToString();
                        string AddressProof = "~/UploadedFiles/" + str1.ToString();
                        string IdProof = "~/UploadedFiles/" + str2.ToString();
                        string StaffId = TxtStaffId.Text;
                        string Date = TxtDate.Text;
                        string FullName = TxtName.Text;
                        string Gender = TxtGender.SelectedItem.ToString();
                        string Desgination = TxtDesgination.Text;
                        string Department = TxtDepartment.Text;
                        string Subject = TxtSubject.Text;
                        string Experience = TxtExperience.Text;
                        string Email = TxtEmail.Text;
                        string Religion = TxtReligion.Text;
                        string MaritalStatus = DropDownList1.SelectedItem.ToString();
                        string JoinDate = TxtJoinDate.Text;
                        string ContactNo = TxtPhone.Text;
                        string AlternateNumber = TxtAltNumber.Text;
                        string Address = TxtAddress.Text;
                        string Status = TxtStatus.SelectedItem.ToString();
                        string Username = txtusername.Text;
                        string Password = txtpwd.Text;

                        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
                        SqlCommand cmd = new SqlCommand("insert into StaffRegistration values (@Staf_Id,@Date,@FullName,@Gender,@Desgination,@Department,@Subject,@Experience,@Email,@Religion,@MaritalStatus,@JoiningDate,@ContactNo,@AltNumber,@Address,@Photo,@AddressProof,@Id_Proof,@Status,@Username,@Password)", con);
                        cmd.Parameters.AddWithValue("@Staf_Id", StaffId);
                        cmd.Parameters.AddWithValue("@Date", Date);
                        cmd.Parameters.AddWithValue("@FullName", FullName);
                        cmd.Parameters.AddWithValue("@Gender", Gender);
                        cmd.Parameters.AddWithValue("@Desgination", Desgination);
                        cmd.Parameters.AddWithValue("@Department", Department);
                        cmd.Parameters.AddWithValue("@Subject", Subject);
                        cmd.Parameters.AddWithValue("@Experience", Experience);
                        cmd.Parameters.AddWithValue("@Email", Email);
                        cmd.Parameters.AddWithValue("@Religion", Religion);
                        cmd.Parameters.AddWithValue("@MaritalStatus", MaritalStatus);
                        cmd.Parameters.AddWithValue("@JoiningDate", JoinDate);
                        cmd.Parameters.AddWithValue("@ContactNo", ContactNo);
                        cmd.Parameters.AddWithValue("@AltNumber", AlternateNumber);
                        cmd.Parameters.AddWithValue("@Address", Address);
                        cmd.Parameters.AddWithValue("Photo", Photo);
                        cmd.Parameters.AddWithValue("AddressProof", AddressProof);
                        cmd.Parameters.AddWithValue("Id_Proof", IdProof);
                        cmd.Parameters.AddWithValue("@Status", Status);
                        cmd.Parameters.AddWithValue("@Username", Username);
                        cmd.Parameters.AddWithValue("@Password", Password);

                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                        msg.Text = "Submitted Successfully";
                        msg.ForeColor = System.Drawing.Color.ForestGreen;
                        Reset();
                        autogenerated();
                        GridView1.DataBind();
                    }
        }
    }
}