using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class Scholarships : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            Textbox7.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }
        }

        private void Reset()
        {
            txtbox1.Text = string.Empty;
            dd.ClearSelection();
            dd1.ClearSelection();
            Textbox4.Text = string.Empty;
            Textbox5.Text = string.Empty;
            Textbox6.Text = string.Empty;
            Textbox8.Text = string.Empty;
        }

        private void autogenerated()
        {
            string code = "ScholarId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(ScholarId) from Scholarship", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtId.Text = code + i.ToString();
        }

        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Cmd = new SqlCommand("insert into Scholarship values ('" + TxtId.Text.Trim() + "','" + Textbox7.Text.Trim() + "','" + txtbox1.Text.Trim() + "','" + dd.SelectedItem.ToString() + "','" + dd1.SelectedItem.ToString() + "','" + Textbox4.Text.Trim() + "','" + Textbox5.Text.Trim() + "','" + Textbox6.Text.Trim() + "','" + Textbox8.Text.Trim() + "')", Conn);
            Conn.Open();
            Cmd.ExecuteNonQuery();
            Conn.Close();
            Reset();
            autogenerated();
            message.Text = "Values Inserted";
        }
    }
}