using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Data.SqlClient;

namespace SchoolProject
{
    public partial class StaffRoom_Inventory : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {

            TxtDate.Text = System.DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }
        }

        private void autogenerated()
        {
            string code = "InventoryId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(StaffroomId) from StaffRoom_Inventory", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtId.Text = code + i.ToString();
        }

        protected void Reset()
        {
            TxtTables.Text = string.Empty;
            TxtChairs.Text = string.Empty;
            TxtComputers.Text = string.Empty;
            TxtFans.Text = string.Empty;
            TxtLokers.Text = string.Empty;
            TxtLights.Text = string.Empty;
        }
        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Comm = new SqlCommand("insert into StaffRoom_Inventory values('" + TxtId.Text + "','" + TxtDate.Text + "','" + TxtTables.Text + "','" + TxtChairs.Text + "','" + TxtComputers.Text + "','" + TxtFans.Text + "','" + TxtLokers.Text + "','" + TxtLights.Text + "')", Conn);
            Conn.Open();
            Comm.ExecuteNonQuery();
            Conn.Close();
            Reset();
        }
    }
}