using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

namespace SchoolProject
{
    public partial class Visitors : System.Web.UI.Page
    {
        SqlConnection Conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            txtdate.Text = DateTime.Now.ToShortDateString();
            if (!IsPostBack)
            {
                autogenerated();
                Reset();
            }
        }

        private void Reset()
        {
            txtfstname.Text = string.Empty;
            txtlastname.Text = string.Empty;
            txtrsn.Text = string.Empty;
            txttime.Text = string.Empty;
            txtconum.Text = string.Empty;
            txtadd.Text = string.Empty;
        }

        private void autogenerated()
        {
            string code = "VisitorId-0";
            string strconn = ConfigurationManager.ConnectionStrings["SmsConnection"].ConnectionString;
            SqlConnection conn = new SqlConnection(strconn);
            conn.Open();
            SqlCommand cmd = new SqlCommand("Select count(VisitorId) from Visitors", conn);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            conn.Close();
            i++;
            TxtId.Text = code + i.ToString();
        }

        protected void Button_Click(object sender, EventArgs e)
        {
            SqlCommand Cmd = new SqlCommand("insert into Visitors values ('" + TxtId.Text.Trim() + "','" + txtdate.Text.Trim() + "','" + txtfstname.Text.Trim() + "','" + txtlastname.Text.Trim() + "','" + txtrsn.Text.Trim() + "','" + txttime.Text.Trim() + "','" + txtconum.Text.Trim() + "','" + txtadd.Text.Trim() + "')", Conn);
            Conn.Open();
            Cmd.ExecuteNonQuery();
            Conn.Close();
            Reset();
            autogenerated();
            message.Text = "Values Inserted";
        }
    }
}